import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Builds and downloads a purpose-made PDF for the Reports page — not a screenshot of the
 * app UI. Four distinct sections (one per page), each with its own header band, KPI strip
 * and clean tables, styled with the app's own brand colors so it reads as a real library
 * report rather than a printed webpage.
 */

const INK = "#122222";
const EMERALD = "#1a4d40";
const COPPER = "#b96f3e";
const PARCHMENT = "#F9F8F4";
const MUTED = "#6b7a76";

const PAGE_W = 210; // A4 portrait, mm
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

export interface ReportsPdfInput {
  libraryName: string;
  librarySubtitle?: string;
  generatedAt: Date;
  rangeLabel: string;
  locale: "en" | "fr" | "ar";
  kpis: { label: string; value: string; sub: string }[];
  sections: {
    id: string;
    title: string;
    subtitle: string;
    tables: {
      title: string;
      columns: string[];
      rows: (string | number)[][];
    }[];
  }[];
}

function drawPageChrome(doc: jsPDF, input: ReportsPdfInput, pageIndex: number, pageCount: number) {
  // Top brand band
  doc.setFillColor(INK);
  doc.rect(0, 0, PAGE_W, 22, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(input.libraryName || "Warraq Library", MARGIN, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#c9d6d2");
  doc.text(input.librarySubtitle || "Library Analytics & Reports", MARGIN, 18);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(COPPER);
  doc.text(input.rangeLabel, PAGE_W - MARGIN, 13, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor("#c9d6d2");
  doc.text(
    input.generatedAt.toLocaleString(input.locale === "ar" ? "ar-DZ" : input.locale === "fr" ? "fr-FR" : "en-US", {
      dateStyle: "medium",
      timeStyle: "short",
    }),
    PAGE_W - MARGIN,
    18,
    { align: "right" }
  );

  // Footer
  doc.setDrawColor(230, 226, 216);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE_H - 12, PAGE_W - MARGIN, PAGE_H - 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text("Generated by Warraq — Library Management System", MARGIN, PAGE_H - 7);
  doc.text(`Page ${pageIndex} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 7, { align: "right" });
}

function drawSectionHeader(doc: jsPDF, title: string, subtitle: string, y: number): number {
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, MARGIN + 5, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d7e6e1");
  doc.text(subtitle, MARGIN + 5, y + 12.5);
  return y + 16 + 6;
}

function drawKpiStrip(doc: jsPDF, kpis: ReportsPdfInput["kpis"], y: number): number {
  const gap = 4;
  const cardW = (CONTENT_W - gap * (kpis.length - 1)) / kpis.length;
  const cardH = 22;
  kpis.forEach((k, i) => {
    const x = MARGIN + i * (cardW + gap);
    doc.setFillColor(PARCHMENT);
    doc.setDrawColor(230, 226, 216);
    doc.setLineWidth(0.2);
    doc.roundedRect(x, y, cardW, cardH, 2, 2, "FD");
    doc.setTextColor(INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(k.value, x + 4, y + 10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(COPPER);
    doc.text(k.label.toUpperCase(), x + 4, y + 15.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(MUTED);
    const subLines = doc.splitTextToSize(k.sub, cardW - 8);
    doc.text(subLines[0] ?? "", x + 4, y + 19.5);
  });
  return y + cardH + 8;
}

function drawTable(doc: jsPDF, table: ReportsPdfInput["sections"][number]["tables"][number], y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(INK);
  doc.text(table.title, MARGIN, y);
  autoTable(doc, {
    startY: y + 2.5,
    margin: { left: MARGIN, right: MARGIN },
    head: [table.columns],
    body: table.rows.length > 0 ? table.rows : [[{ content: "No data for this period", colSpan: table.columns.length, styles: { halign: "center", textColor: MUTED, fontStyle: "italic" } }]],
    theme: "plain",
    styles: { fontSize: 8.5, cellPadding: 2.2, textColor: INK, lineColor: [235, 231, 222], lineWidth: 0.15 },
    headStyles: { fillColor: INK, textColor: "#ffffff", fontStyle: "bold", fontSize: 8 },
    alternateRowStyles: { fillColor: [252, 251, 248] },
    columnStyles: table.columns.length > 1 ? { [table.columns.length - 1]: { halign: "right", fontStyle: "bold" } } : undefined,
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (doc as any).lastAutoTable.finalY + 8;
}

export function generateReportsPdf(input: ReportsPdfInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  input.sections.forEach((section, idx) => {
    if (idx > 0) doc.addPage();
    let y = 22 + 8;
    y = drawSectionHeader(doc, section.title, section.subtitle, y);
    if (idx === 0) y = drawKpiStrip(doc, input.kpis, y);

    for (const table of section.tables) {
      const estRowsH = 14 + table.rows.length * 7;
      if (y + Math.min(estRowsH, 40) > PAGE_H - 18) {
        doc.addPage();
        y = 22 + 8;
      }
      y = drawTable(doc, table, y);
    }
  });

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageChrome(doc, input, p, totalPages);
  }

  const stamp = input.generatedAt.toISOString().split("T")[0];
  doc.save(`warraq-library-report-${stamp}.pdf`);
}
