import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Builds and downloads a purpose-made PDF for the Reports page — not a screenshot of the
 * app UI. Four distinct sections (one per page), each with its own header band, KPI strip,
 * chart images, and clean tables, styled with the app's own brand colors so it reads as a
 * real library report rather than a printed webpage.
 */

const INK = "#122222";
const EMERALD = "#1a4d40";
const COPPER = "#b96f3e";
const PARCHMENT = "#F9F8F4";
const MUTED = "#6b7a76";

const PAGE_W = 210; // A4 portrait, mm
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

const ARABIC_FONT = "Vazirmatn";
/** Matches any Arabic-script codepoint. jsPDF's built-in helvetica/times/courier fonts have no
 * Arabic glyphs at all — they render Arabic text as mojibake — so Arabic strings must use the
 * embedded Vazirmatn font instead. */
const ARABIC_RE = /[؀-ۿݐ-ݿ]/;
function containsArabic(text: string): boolean {
  return ARABIC_RE.test(text);
}

export interface ReportsPdfChart {
  title: string;
  /** PNG data URL captured from the on-screen chart. */
  dataUrl: string;
  width: number;
  height: number;
}

export interface ReportsPdfInput {
  libraryName: string;
  librarySubtitle?: string;
  generatedAt: Date;
  rangeLabel: string;
  locale: "en" | "fr" | "ar";
  kpis: { label: string; value: string; sub: string }[];
  sections: {
    id: string;
    title: string;
    subtitle: string;
    charts?: ReportsPdfChart[];
    tables: {
      title: string;
      columns: string[];
      rows: (string | number)[][];
    }[];
  }[];
}

/** Picks the embedded Arabic-capable font for Arabic locale, otherwise jsPDF's built-in helvetica. */
function bodyFont(locale: ReportsPdfInput["locale"]): string {
  return locale === "ar" ? ARABIC_FONT : "helvetica";
}

/** Draws text, toggling jsPDF's per-call R2L reversal only when the string is actually
 * Arabic-script — a persistent/global R2L flag would also reverse adjacent numbers and Latin
 * text (dates, counts, page numbers) drawn elsewhere in the same document, which is wrong. */
function drawText(doc: jsPDF, text: string, x: number, y: number, options: Record<string, unknown> = {}) {
  doc.text(text, x, y, containsArabic(text) ? { ...options, R2L: true } : options);
}

async function embedArabicFont(doc: jsPDF) {
  const { VAZIRMATN_REGULAR_BASE64 } = await import("../assets/fonts/vazirmatnRegularBase64");
  doc.addFileToVFS("Vazirmatn-Regular.ttf", VAZIRMATN_REGULAR_BASE64);
  doc.addFont("Vazirmatn-Regular.ttf", ARABIC_FONT, "normal");
  doc.addFont("Vazirmatn-Regular.ttf", ARABIC_FONT, "bold");
}

function drawPageChrome(doc: jsPDF, input: ReportsPdfInput, pageIndex: number, pageCount: number) {
  const font = bodyFont(input.locale);

  // Top brand band
  doc.setFillColor(INK);
  doc.rect(0, 0, PAGE_W, 22, "F");
  doc.setTextColor("#ffffff");
  doc.setFont(font, "bold");
  doc.setFontSize(14);
  drawText(doc, input.libraryName || "Warraq Library", MARGIN, 13);
  doc.setFont(font, "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#c9d6d2");
  drawText(doc, input.librarySubtitle || "Library Analytics & Reports", MARGIN, 18);

  doc.setFont(font, "bold");
  doc.setFontSize(9);
  doc.setTextColor(COPPER);
  drawText(doc, input.rangeLabel, PAGE_W - MARGIN, 13, { align: "right" });
  doc.setFont(font, "normal");
  doc.setFontSize(8);
  doc.setTextColor("#c9d6d2");
  drawText(
    doc,
    input.generatedAt.toLocaleString(input.locale === "ar" ? "ar-DZ" : input.locale === "fr" ? "fr-FR" : "en-US", {
      dateStyle: "medium",
      timeStyle: "short",
    }),
    PAGE_W - MARGIN,
    18,
    { align: "right" }
  );

  // Footer
  doc.setDrawColor(230, 226, 216);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE_H - 12, PAGE_W - MARGIN, PAGE_H - 12);
  doc.setFont(font, "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text("Generated by Warraq — Library Management System", MARGIN, PAGE_H - 7);
  doc.text(`Page ${pageIndex} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 7, { align: "right" });
}

function drawSectionHeader(doc: jsPDF, locale: ReportsPdfInput["locale"], title: string, subtitle: string, y: number): number {
  const font = bodyFont(locale);
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, "F");
  doc.setTextColor("#ffffff");
  doc.setFont(font, "bold");
  doc.setFontSize(13);
  drawText(doc, title, MARGIN + 5, y + 7);
  doc.setFont(font, "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d7e6e1");
  drawText(doc, subtitle, MARGIN + 5, y + 12.5);
  return y + 16 + 6;
}

function drawKpiStrip(doc: jsPDF, locale: ReportsPdfInput["locale"], kpis: ReportsPdfInput["kpis"], y: number): number {
  const font = bodyFont(locale);
  const gap = 4;
  const cardW = (CONTENT_W - gap * (kpis.length - 1)) / kpis.length;
  const cardH = 22;
  kpis.forEach((k, i) => {
    const x = MARGIN + i * (cardW + gap);
    doc.setFillColor(PARCHMENT);
    doc.setDrawColor(230, 226, 216);
    doc.setLineWidth(0.2);
    doc.roundedRect(x, y, cardW, cardH, 2, 2, "FD");
    doc.setTextColor(INK);
    doc.setFont(font, "bold");
    doc.setFontSize(13);
    drawText(doc, k.value, x + 4, y + 10);
    doc.setFont(font, "bold");
    doc.setFontSize(7);
    doc.setTextColor(COPPER);
    drawText(doc, k.label.toUpperCase(), x + 4, y + 15.5);
    doc.setFont(font, "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(MUTED);
    const subLines = doc.splitTextToSize(k.sub, cardW - 8);
    drawText(doc, subLines[0] ?? "", x + 4, y + 19.5);
  });
  return y + cardH + 8;
}

const CHART_MAX_H = 62;

/** Lays out chart images two per row, preserving each chart's captured aspect ratio. */
function drawChartsGrid(doc: jsPDF, locale: ReportsPdfInput["locale"], charts: ReportsPdfChart[], y: number): number {
  const font = bodyFont(locale);
  const gap = 6;
  const cols = 2;
  const cardW = (CONTENT_W - gap * (cols - 1)) / cols;
  let curY = y;
  let rowMaxH = 0;

  charts.forEach((chart, i) => {
    const col = i % cols;
    if (col === 0 && i > 0) {
      curY += rowMaxH + gap;
      rowMaxH = 0;
    }
    const imgW = cardW;
    const imgH = Math.min(CHART_MAX_H, (chart.height / chart.width) * imgW);

    if (col === 0 && curY + 6 + imgH > PAGE_H - 18) {
      doc.addPage();
      curY = 22 + 8;
    }

    const x = MARGIN + col * (cardW + gap);
    doc.setFont(font, "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(INK);
    drawText(doc, chart.title, x, curY + 4);
    try {
      doc.addImage(chart.dataUrl, "PNG", x, curY + 6, imgW, imgH);
    } catch (err) {
      console.error("Failed to embed chart image in PDF", err);
    }
    rowMaxH = Math.max(rowMaxH, imgH + 6);
  });

  return curY + rowMaxH + 8;
}

function drawTable(doc: jsPDF, locale: ReportsPdfInput["locale"], table: ReportsPdfInput["sections"][number]["tables"][number], y: number): number {
  const font = bodyFont(locale);
  doc.setFont(font, "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(INK);
  drawText(doc, table.title, MARGIN, y);

  // Toggled per-cell in didParseCell/didDrawCell below, so Arabic labels reverse correctly
  // while numeric columns in the very same table are never touched.
  autoTable(doc, {
    startY: y + 2.5,
    margin: { left: MARGIN, right: MARGIN },
    head: [table.columns],
    body: table.rows.length > 0 ? table.rows : [[{ content: "No data for this period", colSpan: table.columns.length, styles: { halign: "center", textColor: MUTED, fontStyle: "italic" } }]],
    theme: "plain",
    styles: { font, fontSize: 8.5, cellPadding: 2.2, textColor: INK, lineColor: [235, 231, 222], lineWidth: 0.15 },
    headStyles: { font, fillColor: INK, textColor: "#ffffff", fontStyle: "bold", fontSize: 8 },
    alternateRowStyles: { fillColor: [252, 251, 248] },
    columnStyles: table.columns.length > 1 ? { [table.columns.length - 1]: { halign: "right", fontStyle: "bold" } } : undefined,
    willDrawCell: (data) => {
      const isArabic = Array.isArray(data.cell.text) ? data.cell.text.some((line) => containsArabic(String(line))) : containsArabic(String(data.cell.text));
      doc.setR2L(isArabic);
    },
  });
  doc.setR2L(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (doc as any).lastAutoTable.finalY + 8;
}

export async function generateReportsPdf(input: ReportsPdfInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  if (input.locale === "ar") {
    await embedArabicFont(doc);
  }

  input.sections.forEach((section, idx) => {
    if (idx > 0) doc.addPage();
    let y = 22 + 8;
    y = drawSectionHeader(doc, input.locale, section.title, section.subtitle, y);
    if (idx === 0) y = drawKpiStrip(doc, input.locale, input.kpis, y);

    if (section.charts && section.charts.length > 0) {
      y = drawChartsGrid(doc, input.locale, section.charts, y);
    }

    for (const table of section.tables) {
      const estRowsH = 14 + table.rows.length * 7;
      if (y + Math.min(estRowsH, 40) > PAGE_H - 18) {
        doc.addPage();
        y = 22 + 8;
      }
      y = drawTable(doc, input.locale, table, y);
    }
  });

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageChrome(doc, input, p, totalPages);
  }

  const stamp = input.generatedAt.toISOString().split("T")[0];
  doc.save(`warraq-library-report-${stamp}.pdf`);
}
