#!/usr/bin/env python3
"""
One-off import of the book inventory recovered from documents/التصنيف/*.docx into
Supabase (books + copies). Not part of the app bundle — run manually, once:

    python scripts/import_catalog.py > scripts/import_catalog.sql
    # inspect the generated SQL, then:
    PGPASSWORD=<db password> psql -h aws-0-<region>.pooler.supabase.com -p 5432 \
        -U postgres.<project-ref> -d postgres -v ON_ERROR_STOP=1 -f scripts/import_catalog.sql

Each .docx table row is N° | Titre | Auteur | Année | Cote | Observation. Only rows that
parse as real data (not a header row or a "..." placeholder) are kept.

Two-stage dedup, since several of the source files are duplicate drafts of each other and
the same physical copy's row would otherwise be double-counted:
  1. Exact-row dedup (title+author+year+cote+observation) collapses cross-file duplicates —
     e.g. "المستند (18).docx" / "(18) (1).docx" / "(18) (2).docx" are identical files.
  2. Rows that then still share (title, author, year, cote) are treated as separate physical
     copies of the same title (this matches the source data: duplicate copies are listed as
     repeated rows with identical bibliographic fields, e.g. "Tome IV" appearing twice with
     a note like "غلاف المجلد الخارجي" on the second row). The copy count per title is
     additionally bumped up if the Observation text explicitly mentions more copies than
     were actually listed as rows (e.g. "[4 نسخ مكررة / 4 Exemplaires]").

Only books are importable from documents/ — there is no FYP or journal source data in the
provided files, so this script only ever creates item_type='book' rows.
"""
import glob
import re
import sys
import uuid
from xml.etree import ElementTree as ET
import zipfile

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
DOCS_GLOB = "documents/التصنيف/*.docx"


def cell_text(tc):
    return "".join(t.text or "" for t in tc.iter(f"{W}t")).strip()


def parse_docx_rows(path):
    """Yields (num, title, author, year, cote, observation) for every real data row."""
    with zipfile.ZipFile(path) as z:
        xml = z.read("word/document.xml")
    root = ET.fromstring(xml)
    for tbl in root.iter(f"{W}tbl"):
        for tr in tbl.iter(f"{W}tr"):
            cells = [cell_text(tc) for tc in tr.findall(f"{W}tc")]
            if len(cells) < 6:
                continue
            num, title, author, year, cote, observation = cells[:6]
            if not title or title in ("Le titre", "...", "…"):
                continue
            if num.strip().lower() in ("n°", "n", ""):
                # Header rows have "N°" in the first cell; a few source rows have a blank
                # N° but real data — only skip if title also looks like a header/placeholder.
                if title == "Le titre":
                    continue
            yield {
                "num": num.strip(),
                "title": title.strip(),
                "author": author.strip(),
                "year": year.strip(),
                "cote": cote.strip(),
                "observation": observation.strip(),
                "source": path,
            }


COPY_COUNT_PATTERNS = [
    (re.compile(r"(\d+)\s*(?:نسخ|Exemplaires?)", re.IGNORECASE), lambda m: int(m.group(1))),
    (re.compile(r"نسختان"), lambda m: 2),
    (re.compile(r"ثلاث نسخ"), lambda m: 3),
]


def explicit_copy_count(observation: str) -> int:
    best = 1
    for pattern, extract in COPY_COUNT_PATTERNS:
        m = pattern.search(observation)
        if m:
            best = max(best, extract(m))
    return best


def norm(s: str) -> str:
    return re.sub(r"\s+", " ", s or "").strip().lower()


def sql_str(value):
    if value is None or value == "":
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def parse_year(year_str):
    m = re.search(r"\d{4}", year_str or "")
    return int(m.group(0)) if m else None


def main():
    files = [f for f in glob.glob(DOCS_GLOB) if "~$" not in f]
    all_rows = []
    per_file_counts = {}
    for f in sorted(files):
        rows = list(parse_docx_rows(f))
        per_file_counts[f] = len(rows)
        all_rows.extend(rows)

    # Stage 1: exact-row dedup (collapses cross-file duplicate drafts).
    seen_exact = {}
    for r in all_rows:
        key = (norm(r["title"]), norm(r["author"]), norm(r["year"]), norm(r["cote"]), norm(r["observation"]))
        seen_exact.setdefault(key, r)
    unique_rows = list(seen_exact.values())

    # Stage 2: group by bibliographic identity -> one book, N copies.
    groups = {}
    for r in unique_rows:
        key = (norm(r["title"]), norm(r["author"]), norm(r["year"]), norm(r["cote"]))
        groups.setdefault(key, []).append(r)

    sql_lines = [
        "-- Generated by scripts/import_catalog.py — imports the recovered book inventory.",
        "-- Review before applying. Copies are left unassigned to a shelf (shelf_id NULL);",
        "-- staff will place them physically and update the shelf during inventory.",
        "begin;",
    ]
    book_count = 0
    copy_count = 0
    for key, rows in groups.items():
        canonical = rows[0]
        title = canonical["title"]
        author = canonical["author"] or None
        year = parse_year(canonical["year"])
        call_number = canonical["cote"] or None
        notes = " | ".join(sorted({r["observation"] for r in rows if r["observation"]}))

        n_copies = max(len(rows), max((explicit_copy_count(r["observation"]) for r in rows), default=1))

        book_id = str(uuid.uuid4())
        if author:
            author_id = str(uuid.uuid4())
            normalized_author = norm(author)
            sql_lines.append(
                f"insert into authors (id, name, normalized_name) values "
                f"({sql_str(author_id)}, {sql_str(author)}, {sql_str(normalized_author)}) "
                f"on conflict (normalized_name) do nothing;"
            )

        sql_lines.append(
            "insert into books (id, item_type, title, language, publication_year, call_number, notes, source) "
            f"values ({sql_str(book_id)}, 'book', {sql_str(title)}, 'French', "
            f"{year if year is not None else 'NULL'}, {sql_str(call_number)}, {sql_str(notes)}, 'import');"
        )
        if author:
            normalized_author = norm(author)
            sql_lines.append(
                "insert into book_authors (book_id, author_id, author_order) "
                f"select {sql_str(book_id)}, id, 0 from authors where normalized_name = {sql_str(normalized_author)};"
            )
        for i in range(n_copies):
            copy_id = str(uuid.uuid4())
            accession = f"IMP-{book_id[:8].upper()}-{i+1:02d}"
            barcode = f"BAR-{book_id[:8].upper()}-{i+1:02d}"
            sql_lines.append(
                "insert into copies (id, book_id, accession_number, barcode, status, condition) "
                f"values ({sql_str(copy_id)}, {sql_str(book_id)}, {sql_str(accession)}, {sql_str(barcode)}, 'available', 'good');"
            )
            copy_count += 1
        book_count += 1

    sql_lines.append("commit;")

    with open("scripts/import_catalog.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines) + "\n")

    print(f"Parsed {len(files)} docx files.", file=sys.stderr)
    for f, c in per_file_counts.items():
        print(f"  {f}: {c} rows", file=sys.stderr)
    print(f"Total raw rows: {len(all_rows)}", file=sys.stderr)
    print(f"After exact-row dedup: {len(unique_rows)}", file=sys.stderr)
    print(f"Unique books: {book_count}", file=sys.stderr)
    print(f"Total copies: {copy_count}", file=sys.stderr)
    print("Wrote scripts/import_catalog.sql — review it, then apply with psql.", file=sys.stderr)
    print("NOTE: FYP and journal inventories are not present in documents/ and are not imported.", file=sys.stderr)


if __name__ == "__main__":
    main()
